package com.masdika.maungapain.ui.theme

import androidx.compose.ui.graphics.Color

val LightGreen = Color(0xFFB2D2A4)
val DarkGreen = Color(0xFF3da835)
val Orange = Color(0xFFFFA500)

// Light
val primaryLight = Color(0xFF000D26)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF02224D)
val onPrimaryContainerLight = Color(0xFFC9D9FF)
val secondaryLight = Color(0xFF242C3E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF41495C)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF1C002B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF341642)
val onTertiaryContainerLight = Color(0xFFF3CCFF)
val errorLight = Color(0xFF600004)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFF98000A)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFAF9FD)
val onBackgroundLight = Color(0xFF1A1B1F)
val surfaceLight = Color(0xFFFAF9FD)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF000000)
val outlineLight = Color(0xFF292C34)
val outlineVariantLight = Color(0xFF464951)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3034)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFFAEC7FB)
val surfaceDimLight = Color(0xFFB9B8BC)
val surfaceBrightLight = Color(0xFFFAF9FD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F0F4)
val surfaceContainerLight = Color(0xFFE3E2E6)
val surfaceContainerHighLight = Color(0xFFD5D4D8)
val surfaceContainerHighestLight = Color(0xFFC7C6CA)

// Dark
val primaryDark = Color(0xFFEBF0FF)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFAAC3F7)
val onPrimaryContainerDark = Color(0xFF000B21)
val secondaryDark = Color(0xFFEBF0FF)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFFBAC2D9)
val onSecondaryContainerDark = Color(0xFF030B1B)
val tertiaryDark = Color(0xFFFDEAFF)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFFDDB4EB)
val onTertiaryContainerDark = Color(0xFF180026)
val errorDark = Color(0xFFFFECE9)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFFFFAEA4)
val onErrorContainerDark = Color(0xFF220001)
val backgroundDark = Color(0xFF121316)
val onBackgroundDark = Color(0xFFE3E2E6)
val surfaceDark = Color(0xFF121316)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF44474F)
val onSurfaceVariantDark = Color(0xFFFFFFFF)
val outlineDark = Color(0xFFEEEFFA)
val outlineVariantDark = Color(0xFFC0C2CC)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E6)
val inverseOnSurfaceDark = Color(0xFF000000)
val inversePrimaryDark = Color(0xFF2F4874)
val surfaceDimDark = Color(0xFF121316)
val surfaceBrightDark = Color(0xFF4F5053)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF1E1F23)
val surfaceContainerDark = Color(0xFF2F3034)
val surfaceContainerHighDark = Color(0xFF3A3B3F)
val surfaceContainerHighestDark = Color(0xFF46464A)